In [1]:
import pandas as pd

In [2]:
data = pd.read_excel("ADHD Data.xlsx")
data.head()

,No,Sex,Day of birth,Diagnosis,Text layout,Unnamed: 5,Unnamed: 6,Unnamed: 7,Margins,Unnamed: 9,...,Continuity or,Unnamed: 42,Unnamed: 43,Unnamed: 44,Shape of,Unnamed: 46,Unnamed: 47,Speed of,Unnamed: 49,Strength of
0,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,flow connection,NaN,NaN,NaN,letters,NaN,NaN,writung,NaN,graphism
1,NaN,NaN,NaT,NaN,3,1,2,0,1,2,...,0,1,2,3,4,0,1,2,0,1
2,1.0,M,2002-11-06,control,N,N,N,Y,Y,N,...,N,N,N,Y,N,N,Y,N,N,Y
3,2.0,F,1999-05-31,ADHD,N,N,N,Y,Y,N,...,N,Y,N,Y,N,N,Y,N,N,Y
4,3.0,M,2003-02-13,ADHD,N,N,Y,N,Y,N,...,N,N,Y,N,N,N,Y,N,N,Y

In [6]:
data.shape

(51, 51)

In [10]:
data = data.drop([0, 1], axis=0)

In [12]:
data.shape

(49, 51)